version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2-arm64
    ports:
      - 9200:9200
    volumes:
      - /mnt/ssd/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2-arm64
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
       - 5601:5601
    volumes:
      - /mnt/ssd/kibana/data:/usr/share/kibana/data
